### ISSUE TITLE
Scan interval

### ISSUE THREAD

**Issue by JonOve** [mvdwetering/websitechecker#1]
Scan interval has started to fail unfortunately. Used to work fine.

**Comment by mvdwetering** [comment]
Could you elaborate a bit more on this?

I don't have a feature to change the interval that I am aware of.

Also I haven't touched the actual sensor code in months.
How did you conclude it stopped working?
Did it break with a HA update?

**Comment by JonOve** [comment]
Hello, thanks for the component. The status of the sensor was updated
regularly and working fine. For a few days I noticed (and yes there were
some HA updates), that the status is only updated at a restart. There is no
error log. Scan interval can be changed in the binary sensor file, but did
not touch this one.

Op ma 24 mei 2021 om 18:53 schreef Michel van de Wetering <
***@***.***>:

**Comment by mvdwetering** [comment]
I have looked into it a bit more, but can't reporduce it on my end.
However I made a new version v0.5.1 which includes additional debug logging.

You can enable the debug logging by including the following section in `configuration.yaml` and restarting HA (or just adding the websitechecker line if the section already exists)
```
logger:
  default: info
  logs:
    custom_components.websitechecker: debug
```

After restarting HA you should see lines in the log with `[custom_components.websitechecker]`. 
Could you let it run for a while (say an hour) and send the logs?
You can disable the debug logging afterwards.

I did notice somewhat different behavior between my normal setup and dev setup (but both work). 
Could you provide the info from the "System Health" section in HA Configuration>Info as maybe it is related to the platform you are running on.

**Comment by JonOve** [comment]
Okay, I updated to the new version and added the logger. It is Working fine now. It is checking the URL's every 10 minutes. Not sure if it is updating the entity however. Will let you know tomorrow.

**Comment by JonOve** [comment]
The entity in Ha is updating fine. Just removed the lan cable from the pi to check. Thanks a lot for your support

**Comment by mvdwetering** [comment]
Hmm, that is a bit weird since I only added some debug logging.
Anyway since it seems your issue is gone I will close it.
