### ISSUE TITLE
502 should not be Ok

### ISSUE THREAD

**Issue by mariomare22** [mvdwetering/websitechecker#2]
Hello,

I am trying to monitor my nextcloud instance running on docker which is behind a reverse proxy (nginx)
when I stop nextcloud container I obviously cannot reach it but still nginx is answering my request with `502 - Bad Gateway`.

and websitechecker states it's ok.

What can be done in your opinion to adjust it?

Thanks

**Comment by mariomare22** [comment]
nevermind it's actually working I don't know why but even with 502 it's giving Problem (I just had to wait 10mins of the timeout)

+1 for improvement of readme regarding the scan interval.

**Comment by mvdwetering** [comment]
Indeed it can take up to 10 minutes for it to update. I added the current scan interval to the readme.
