### ISSUE TITLE
Websites served from another port

### ISSUE THREAD

**Issue by xAPPO** [mvdwetering/websitechecker#3]
Should this work with websites served from a port other than 80 eg HA itself from 8123?

 `-url: http://192.168.1.50:8123`

I tried as above and also with single and double quotes around the url parameter but all just show as the site being in error

Ooops Double quotes works - sorry

**Comment by mvdwetering** [comment]
Weird that you needed quotes around it to work.

I extended the readme with an example of my own configuration to clarify the port usage. That example works fine for me without quotes. But yaml sometimes gets picky for some reason...
