### ISSUE TITLE
DEVICE_CLASS_PROBLEM was used from websitechecker, this is a deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by KRGT-NL** [mvdwetering/websitechecker#5]
Logger: homeassistant.components.binary_sensor
Source: helpers/deprecation.py:205
Integration: Binaire sensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 19:34:45 (2 occurrences)
Last logged: 19:34:45

DEVICE_CLASS_PROBLEM was used from websitechecker, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.PROBLEM instead, please create a bug report at https://github.com/mvdwetering/websitechecker/issues

**Comment by mvdwetering** [comment]
Thanks for the heads up. I just pushed v1.5.1 which fixes this.

**Comment by KRGT-NL** [comment]
> Thanks for the heads up. I just pushed v1.5.1 which fixes this.

Yes, that did the trick :)
