### ISSUE TITLE
Accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11

### ISSUE THREAD

**Issue by Palerm** [mvdwetering/websitechecker#7]
Thanks for your work. I get a Hint in the protocol:
22024-06-16 15:42:05.530 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'websitechecker' accesses hass.helpers.discovery. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from discovery directly at custom_components/websitechecker/__init__.py, line 44: hass.helpers.discovery.async_load_platform(, please create a bug report at https://github.com/mvdwetering/websitechecker/issues"

Maybe it will be possible for you, to correct this?

**Comment by mvdwetering** [comment]
Well, that is embarrasing 😳. I already fixed that in beginning of May and thought I released it but it turns out I never actually published the release (it was still marked as Draft)

Should be fixed in the now published 1.5.2

**Comment by Palerm** [comment]
Thanks for the update, after the last HA Update and a restart, the check run only one time at startup, but never again. Do you need more information?

EDIT:
I think it was a misunderstanding from my site, seems that everything is OK! Sorry

**Comment by mvdwetering** [comment]
All seems fixed now, so closing it
