### ISSUE TITLE
Documentation improvement request: example of messaging automations

### ISSUE THREAD

**Issue by executed** [mvdwetering/websitechecker#8]
As a potential repository user, I want to see possible automation examples that would integrate with popular messaging systems.
It's suggested to add the 2 automation examples that sends message to Telegram chat (official integration) once one of tracked systems is down or back up.

Ideas for documentation examples:
1. Ping: On problem with system on LAN
[Ping_On_problem_with_system_on_LAN.txt](https://github.com/user-attachments/files/16730711/Ping_On_problem_with_system_on_LAN.txt)

2. Ping: system on LAN is back up
[Ping_system_on_LAN_is_back_up.txt](https://github.com/user-attachments/files/16730714/Ping_system_on_LAN_is_back_up.txt)

**Comment by mvdwetering** [comment]
I gave this some thought, but I don't really want to document (and with that support) specific automations in this integration. 

There are several ways to send notifications in Home Assistant and I don't really want to mention one specific way. For example your automations use specific telegram actions and won't work for other integrations.

In the end the integration just exposes sensors and they can be used in automations like any other sensor in Home Assistant.

However I do agree that sending notifications is a common usecase. So I extended the readme with a short section with some links to related Home Assistant documentation which I hope will help people learn about Home Assistant Automation in general.
