### ISSUE TITLE
return 200 - OK, but state if Off?

### ISSUE THREAD

**Issue by geedsen** [mvdwetering/websitechecker#9]
Just added the integration, but I get this:

![image](https://github.com/user-attachments/assets/85f7a614-3d22-4556-a670-a2b7a5f8ea23)

200-OK, should the state than not be On?

**Comment by mvdwetering** [comment]
The sensor has device class "problem". This means it will be on when there is a problem, off when there is no problem.
This is how problem sensors work in Home Assistant 🤷

It is clearer if you look at the entities in the frontend. It shows "Problem" for the sensor that is `on` and the one that shows "OK" is  `off`

![image](https://github.com/user-attachments/assets/cc48bb88-8df4-4b70-9426-c21e2d78da9f)

**Comment by geedsen** [comment]
AHa, I just saw it as a binary sensor. Than there is no issue. Thanks!
